version: '3'
services:
  php:
    build: ./dev/docker
    environment:
      HOST_USER_ID: ${HOST_USER_ID}
      HOST_GROUP_ID: ${HOST_GROUP_ID}
      PSR_HTTP_PROVIDER: ${PSR_HTTP_PROVIDER:-nyholm}
    image: mailjet/mailjet-php73
    volumes:
      - .:/app/src